
services:

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c wal_level=logical
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  fastapi:
    build:
      context: ./server
    container_name: fastapi-server
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./server/.env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./server:/app
      
    

  ai_service:
    build:
      context: ./ai_services
      dockerfile: Dockerfile
    container_name: ai-microservice
    restart: always
    depends_on:
      - qdrant
    env_file:
      - ./ai_services/.env
    environment:
      - PYTHONPATH=/app:/server_code
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - ./ai_services/ai_app:/app/ai_app
      - ./server:/server_code
    ports:
      - "8001:8001"
    command: uvicorn ai_app.main:app --host 0.0.0.0 --port 8001 --workers 1



  chat_service:
    build:
      context: ./chat_service
    container_name: chat-microservice
    restart: always
    depends_on:
      - mongodb
      - redis
    env_file:
      - ./chat_service/.env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./chat_service:/app
    ports:
      - "8002:8002"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-vector-db
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
      
  nginx:
    image: nginx:latest
    container_name: api-gateway
    restart: always
    ports:
      - "8080:80"  
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
      - ai_service
      - chat_service

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: always
    depends_on:
      - postgres
    ports:
      - "5678:5678"
      
    env_file:
      - ./server/.env
    # THIS LINE BELOW IS THE KEY FIX
    entrypoint: /bin/sh -c "sleep 15; n8n start"
    volumes:
      - n8n_data:/home/node/.n8n

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  celery_worker:
    build:
      context: ./server
    container_name: celery-worker
    restart: always
    depends_on:
      - redis
      - postgres
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      
    environment:
      - PYTHONPATH=/app:/app/ai_services
    command: >
      celery -A app.core.celery.celery_app worker --loglevel=info


  celery_beat:
    build:
      context: ./server
    container_name: celery-beat
    restart: always
    depends_on:
      - redis
      - postgres
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    environment:
      - PYTHONPATH=/app:/app/ai_services
    command: >
      celery -A app.core.celery.celery_app beat --loglevel=info


  elt-consumer:
    build:
      context: .
      dockerfile: elt_pipeline/Dockerfile
    container_name: elt_consumer
    depends_on:
      - kafka
      - connect
      - clickhouse
    env_file:
      - ./server/.env
    environment:
      - KAFKA_BROKER=kafka:9092
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    command: >
      sh -c "python -m elt_pipeline.core.debzium.registry &&
             python -m elt_pipeline.main"
    restart: on-failure
    volumes:
      - .:/app
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"   
      - "9000:9000"  
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: mypassword


  ai_worker:
    build:
      context: ./ai_services
      dockerfile: Dockerfile
    image: supply-chain-management-ai-worker:latest
    container_name: ai-worker
    restart: always
    depends_on:
      - redis
      - postgres
    env_file:
      - ./ai_services/.env
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./ai_services/ai_app:/app/ai_app
    command: celery -A ai_app.tasks.agent_tasks worker -Q ai_queue --loglevel=info
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092

    
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
  
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  connect:
    image: debezium/connect:2.5
    container_name: debezium_connect
    depends_on:
      - kafka
      - postgres
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
  
 

volumes:
  postgres_data:
  n8n_data:
  mongo_data:
  clickhouse_data:
  qdrant_data:
  

