version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  fastapi:
    build:
      context: ./server
    container_name: fastapi-server
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./server/.env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./server:/app
      
    

  ai_service:
    build:
      context: ./ai_services
    container_name: ai-microservice
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./ai_services/.env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./ai_services:/app
    
      
  nginx:
    image: nginx:latest
    container_name: api-gateway
    restart: always
    ports:
      - "8080:80"  # 🚀 CHANGED THIS LINE!
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
      - ai_service

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    depends_on:
      - postgres
    ports:
      - "5678:5678"
    env_file:
      - ./server/.env

    volumes:
      - n8n_data:/home/node/.n8n

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  celery_worker:
    build:
      context: ./server
    container_name: celery-worker
    restart: always
    depends_on:
      - redis
      - postgres
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      
    environment:
      - PYTHONPATH=/app:/app/ai_services
    command: >
      celery -A app.core.celery.celery_app worker --loglevel=info

 
 

volumes:
  postgres_data:
  n8n_data:
  mongo_data: