"""use non-native enum

Revision ID: 199926db8b0e
Revises: 6ade91bf0948
Create Date: 2026-05-14 09:42:22.779249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199926db8b0e'
down_revision: Union[str, Sequence[str], None] = '6ade91bf0948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factories_id'), table_name='factories')
    op.drop_table('factories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('factories_company_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('factories_pkey'))
    )
    op.create_index(op.f('ix_factories_id'), 'factories', ['id'], unique=False)
    # ### end Alembic commands ###
