"""add extra_data to invite_tokens

Revision ID: 1ac1d076691d
Revises: 2878f7568a39
Create Date: 2026-05-09 12:48:13.559576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ac1d076691d'
down_revision: Union[str, Sequence[str], None] = '2878f7568a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_tokens', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('invite_tokens', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('invite_tokens', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('invite_tokens', 'token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('invite_tokens', 'shift',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('invite_tokens', 'department',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invite_tokens', 'department',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('invite_tokens', 'shift',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('invite_tokens', 'token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('invite_tokens', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('invite_tokens', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('invite_tokens', 'extra_data')
    # ### end Alembic commands ###
