"""add cars

Revision ID: 1c49f364548a
Revises: dd00d51dfd77
Create Date: 2026-05-10 17:40:13.493682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c49f364548a'
down_revision: Union[str, Sequence[str], None] = 'dd00d51dfd77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_owners_email'), table_name='business_owners')
    op.drop_index(op.f('ix_business_owners_id'), table_name='business_owners')
    op.drop_table('business_owners')
    op.drop_index(op.f('ix_business_cards_id'), table_name='business_cards')
    op.drop_table('business_cards')
    op.drop_table('notfcation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notfcation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('notfcation_pkey'))
    )
    op.create_table('business_cards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tagline', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('business_cards_pkey'))
    )
    op.create_index(op.f('ix_business_cards_id'), 'business_cards', ['id'], unique=False)
    op.create_table('business_owners',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('business_owners_pkey'))
    )
    op.create_index(op.f('ix_business_owners_id'), 'business_owners', ['id'], unique=False)
    op.create_index(op.f('ix_business_owners_email'), 'business_owners', ['email'], unique=True)
    # ### end Alembic commands ###
