"""empty message

Revision ID: 2878f7568a39
Revises: 8c3ac4d3f816
Create Date: 2026-05-09 12:05:12.997086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2878f7568a39'
down_revision: Union[str, Sequence[str], None] = '8c3ac4d3f816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_tokens', sa.Column('name', sa.String(), nullable=False))
    op.add_column('invite_tokens', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('invite_tokens', sa.Column('shift', sa.String(), nullable=False))
    op.add_column('invite_tokens', sa.Column('department', sa.String(), nullable=False))
    op.add_column('invite_tokens', sa.Column('factory_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invite_tokens', 'factory_id')
    op.drop_column('invite_tokens', 'department')
    op.drop_column('invite_tokens', 'shift')
    op.drop_column('invite_tokens', 'phone')
    op.drop_column('invite_tokens', 'name')
    # ### end Alembic commands ###
