"""message

Revision ID: 63cd5b206da6
Revises: 4c9bc90e5ef2
Create Date: 2026-05-12 16:51:41.218123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63cd5b206da6'
down_revision: Union[str, Sequence[str], None] = '4c9bc90e5ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factories_company_id'), 'factories', ['company_id'], unique=False)
    op.create_index(op.f('ix_factories_id'), 'factories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factories_id'), table_name='factories')
    op.drop_index(op.f('ix_factories_company_id'), table_name='factories')
    op.drop_table('factories')
    # ### end Alembic commands ###
