"""sync factory base fix

Revision ID: 6ade91bf0948
Revises: 1f91c281ece0
Create Date: 2026-05-12 16:58:03.197862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ade91bf0948'
down_revision: Union[str, Sequence[str], None] = '1f91c281ece0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factories_company_id'), table_name='factories')
    op.create_foreign_key(None, 'factories', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'factories', type_='foreignkey')
    op.create_index(op.f('ix_factories_company_id'), 'factories', ['company_id'], unique=False)
    # ### end Alembic commands ###
