"""initial

Revision ID: bb3151fb6fbc
Revises: 4b1e939bf196
Create Date: 2026-05-01 15:17:39.259328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb3151fb6fbc'
down_revision: Union[str, Sequence[str], None] = '4b1e939bf196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_sku_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_warehouse_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.drop_table('approvals')
    op.add_column('companies', sa.Column('company_size', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('mode', sa.Enum('personal', 'team', 'enterprise', name='companymode'), nullable=False))
    op.add_column('companies', sa.Column('website', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('country', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('is_profile_complete', sa.Boolean(), nullable=True))
    op.alter_column('companies', 'industry',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.drop_column('companies', 'is_data_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('is_data_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.alter_column('companies', 'industry',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('companies', 'is_profile_complete')
    op.drop_column('companies', 'phone')
    op.drop_column('companies', 'country')
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'mode')
    op.drop_column('companies', 'company_size')
    op.create_table('approvals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('requester_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reviewer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('approvals_requester_id_fkey')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('approvals_reviewer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('approvals_pkey'))
    )
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('threshold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_pkey'))
    )
    op.create_index(op.f('ix_inventory_warehouse_id'), 'inventory', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_inventory_sku_id'), 'inventory', ['sku_id'], unique=True)
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contact_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lead_time_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('suppliers_pkey'))
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    # ### end Alembic commands ###
