"""connect to the role to worker role

Revision ID: df9c5e2796a5
Revises: b436d9ffa80b
Create Date: 2026-05-03 22:35:44.551772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df9c5e2796a5'
down_revision: Union[str, Sequence[str], None] = 'b436d9ffa80b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # ✅ Create enum safely
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'worker_role') THEN
            CREATE TYPE worker_role AS ENUM ('Worker', 'Operator', 'Supervisor');
        END IF;
    END$$;
    """)

    # ✅ Convert workers.role → enum
    op.execute("""
        ALTER TABLE workers
        ALTER COLUMN role
        TYPE worker_role
        USING role::worker_role
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workers', 'role',
               existing_type=sa.Enum('Worker', 'Operator', 'Supervisor', name='worker_role'),
               type_=sa.VARCHAR(),
               nullable=False)
    op.create_table('suppliers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contact_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lead_time_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('suppliers_pkey'))
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('requester_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reviewer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('approvals_requester_id_fkey')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('approvals_reviewer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('approvals_pkey'))
    )
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('threshold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_pkey'))
    )
    op.create_index(op.f('ix_inventory_warehouse_id'), 'inventory', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_inventory_sku_id'), 'inventory', ['sku_id'], unique=True)
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    # ### end Alembic commands ###
